// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT8LH2CieFew7sOAQaKAez3TgeDs38NF4',
    appId: '1:314199187633:web:f0898e3c7de32066cf4290',
    messagingSenderId: '314199187633',
    projectId: 'apna-wash-7b502',
    authDomain: 'apna-wash-7b502.firebaseapp.com',
    storageBucket: 'apna-wash-7b502.firebasestorage.app',
    measurementId: 'G-3C4NGSVQ34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR9MrJIBNDxD7QvThpuG-RkMh2OHPIap0',
    appId: '1:314199187633:android:4f9aeb06c8de3c0fcf4290',
    messagingSenderId: '314199187633',
    projectId: 'apna-wash-7b502',
    storageBucket: 'apna-wash-7b502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoYxnv67fw6xYOpdsxtMoUSSalT335T_E',
    appId: '1:314199187633:ios:1252b15944b80b31cf4290',
    messagingSenderId: '314199187633',
    projectId: 'apna-wash-7b502',
    storageBucket: 'apna-wash-7b502.firebasestorage.app',
    iosBundleId: 'com.example.apnaWash',
  );
}
